from . import id_handlers
from . import admin_handlers
from . import regex_handlers
from . import send_photos
from . import other_handlers
from . import text_handlers
from . import help
from . import start
from . import hashtags
from . import tktiyf
from . import content_handlers
from . import echo
